 name: Build and Push Docker Image

 on:
      push:
        branches:
          - master

 jobs:
      build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Login to registry
              uses: docker/login-action@v1
              with:
               registry: ghcr.io
               username: ${{ github.actor }}
               password: ${{ secrets.REGISTRY_SECRET }}

            - name: Build Docker image
              run: |
               docker build -t ghcr.io/${{ github.repository }}/reductress-bsky-bot:latest .

            - name: Push Docker image
              run: |
               docker push ghcr.io/${{ github.repository }}/reductress-bsky-bot:latest
